services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - ${VOLUME_PATH}/.data/mssql:/var/opt/mssql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./ChefEye.Api/Dockerfile
    container_name: chefeye-api
    ports:
      - "5000:8080"
    depends_on:
      - mssql
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - default

volumes:
  redis_data:

networks:
  default:
    driver: bridge
