version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_SA_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${VOLUME_PATH}/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    networks:
      - shared

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - shared

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - shared

volumes:
  redis_data:
  postgres_data:

networks:
  shared:
    external: true
    name: chefeye_network
