version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./ChefEye.Api/Dockerfile
    container_name: chefeye-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - shared

networks:
  shared:
    external: true
    name: chefeye_network
